export const GET_LANGUAGE = 'GET_LANGUAGE';
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_DEFAULT_LANGUAGE = 'GET_DEFAULT_LANGUAGE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
